package main

// s2WeaponNames maps a Splatoon 2 main-weapon id -> {site-lang: official name}. Source:
// stat.ink weapon DB (multi-language). Languages S2 never shipped in (pt, ar) fall back to
// English at lookup time. Generated table - do not edit by hand.
var s2WeaponNames = map[uint32]map[string]string{
	0: {"en": "Sploosh-o-matic", "fr": "Marqueur lourd", "es": "Marcador", "de": "Disperser", "it": "Marker", "ru": "Плюхотрон", "ja": "ボールドマーカー", "zh": "广域标记枪"},
	1: {"en": "Neo Sploosh-o-matic", "fr": "Marqueur lourd Néo", "es": "Marcador neo", "de": "Disperser Neo", "it": "Marker Neo", "ru": "Плюхотрон «Нео»", "ja": "ボールドマーカーネオ", "zh": "广域标记枪 新型"},
	2: {"en": "Sploosh-o-matic 7", "fr": "Marqueur lourd 7", "es": "Marcador versátil", "de": "Disperser 7", "it": "Marker multi", "ru": "Плюхотрон-7", "ja": "ボールドマーカー7", "zh": "贴牌喇叭枪"},
	10: {"en": "Splattershot Jr.", "fr": "Liquidateur Jr.", "es": "Lanzatintas novato", "de": "Junior-Kleckser", "it": "Sparacolore recluta", "ru": "Каплестрел-У", "ja": "わかばシューター", "zh": "新叶射击枪"},
	11: {"en": "Custom Splattershot Jr.", "fr": "Liquidateur Sr.", "es": "Lanzatintas novato B", "de": "Junior-Kleckser Plus", "it": "Sparacolore logo", "ru": "Каплестрел-У 2.0", "ja": "もみじシューター", "zh": "枫叶射击枪"},
	12: {"en": "Kensa Splattershot Jr.", "fr": "Liquidateur Jr. K", "es": "Lanzatintas novato elegante", "de": "Kensa-Junior-Kleckser", "it": "Sparacolore recluta Nero Marlin", "ru": "Каплестрел-У.С.К.", "ja": "おちばシューター", "zh": "剑乌贼丸贴牌新叶"},
	20: {"en": "Splash-o-matic", "fr": "Marqueur léger", "es": "Marcador fino", "de": "Fein-Disperser", "it": "Marker d'assalto", "ru": "Плюхомет", "ja": "シャープマーカー", "zh": "窄域标记枪"},
	21: {"en": "Neo Splash-o-matic", "fr": "Marqueur léger Néo", "es": "Marcador fino neo", "de": "Fein-Disperser Neo", "it": "Marker d'assalto Neo", "ru": "Плюхомет «Нео»", "ja": "シャープマーカーネオ", "zh": "窄域标记枪 新型"},
	30: {"en": "Aerospray MG", "fr": "Aérogun", "es": "Aerógrafo pro", "de": "Airbrush MG", "it": "Aerografo", "ru": "Аэроспрей", "ja": "プロモデラーMG", "zh": "专业模型枪MG"},
	31: {"en": "Aerospray RG", "fr": "Aérogun premium", "es": "Aerógrafo plus", "de": "Airbrush RG", "it": "Aerografo élite", "ru": "Аэроспрей ДЕЛЮКС", "ja": "プロモデラーRG", "zh": "专业模型枪RG"},
	32: {"en": "Aerospray PG", "fr": "Aérogun select", "es": "Aerógrafo extra", "de": "Airbrush PG", "it": "Aerografo deluxe", "ru": "Аэроспрей ИДЕАЛ", "ja": "プロモデラーPG", "zh": "铜色喷枪"},
	40: {"en": "Splattershot", "fr": "Liquidateur", "es": "Lanzatintas", "de": "Kleckser", "it": "Splasher", "ru": "Каплестрел", "ja": "スプラシューター", "zh": "斯普拉射击枪"},
	41: {"en": "Tentatek Splattershot", "fr": "Liquidateur griffé", "es": "Lanzatintas B", "de": "Tentatek-Kleckser", "it": "Splasher logo", "ru": "Каплестрел «Щуччи»", "ja": "スプラシューターコラボ", "zh": "斯普拉射击枪 联名"},
	42: {"en": "Kensa Splattershot", "fr": "Liquidateur K", "es": "Lanzatintas elegante", "de": "Kensa-Kleckser", "it": "Splasher Nero Marlin", "ru": "Каплестрел от С. Кусаки", "ja": "スプラシューターベッチュー", "zh": "剑乌贼丸贴牌小绿"},
	45: {"en": "Hero Shot Replica", "fr": "Lanceur héroïque (réplique)", "es": "Pistola de Élite (réplica)", "de": "Heldenwaffe Replik", "it": "Pistola élite replica", "ru": "Каплестрел-004 (клон)", "ja": "ヒーローシューター レプリカ", "zh": "英雄射击枪 复制"},
	46: {"en": "Octo Shot Replica", "fr": "Lanceur Octaling (réplique)", "es": "Pistola octariana (réplica)", "de": "Octo Shot Replica", "it": "Octo Shot Replica", "ru": "Octo Shot Replica", "ja": "オクタシューター レプリカ", "zh": "章鱼射击枪 复制"},
	50: {"en": ".52 Gal", "fr": "Calibre 2000", "es": "Salpicadora 2000", "de": ".52 Gallon", "it": "Calibro 2000", "ru": "Струевик .52", "ja": ".52ガロン", "zh": ".52加仑"},
	51: {"en": ".52 Gal Deco", "fr": "Calibre 2000 chic", "es": "Salpicadora 2000 DX", "de": ".52 Gallon Deko", "it": "Calibro 2000 DX", "ru": "Струевик .52 «Деко»", "ja": ".52ガロンデコ", "zh": ".52加仑 装饰"},
	52: {"en": "Kensa .52 Gal", "fr": "Calibre 2000 K", "es": "Salpicadora 2000 elegante", "de": "Kensa-.52-Gallon", "it": "Calibro 2000 Nero Marlin", "ru": "Струевик .52 от С. Кусаки", "ja": ".52ガロンベッチュー", "zh": "剑乌贼丸贴牌点52口径重枪"},
	60: {"en": "N-ZAP '85", "fr": "N-ZAP 85", "es": "N-ZAP 85", "de": "N-ZAP85", "it": "N-ZAP85", "ru": "N-ZAP 85", "ja": "N-ZAP85", "zh": "N-ZAP85"},
	61: {"en": "N-ZAP '89", "fr": "N-ZAP 89", "es": "N-ZAP 89", "de": "N-ZAP89", "it": "N-ZAP89", "ru": "N-ZAP 89", "ja": "N-ZAP89", "zh": "N-ZAP89"},
	62: {"en": "N-ZAP '83", "fr": "N-ZAP 83", "es": "N-ZAP 83", "de": "N-ZAP83", "it": "N-ZAP83", "ru": "N-ZAP 83", "ja": "N-ZAP83", "zh": "N-ZAP83"},
	70: {"en": "Splattershot Pro", "fr": "Liquidateur pro", "es": "Lanzatintas plus", "de": "Profi-Kleckser", "it": "Splasher élite", "ru": "Каплестрел ПРО", "ja": "プライムシューター", "zh": "顶尖射击枪"},
	71: {"en": "Forge Splattershot Pro", "fr": "Liquidateur pro griffé", "es": "Lanzatintas plus B", "de": "Focus-Profi-Kleckser", "it": "Splasher élite logo", "ru": "Каплестрел ПРО «Блиц»", "ja": "プライムシューターコラボ", "zh": "顶尖射击枪 联名"},
	72: {"en": "Kensa Splattershot Pro", "fr": "Liquidateur pro K", "es": "Lanzatintas plus elegante", "de": "Kensa-Profi-Kleckser", "it": "Splasher élite Nero Marlin", "ru": "Каплестрел ПРО от С. К.", "ja": "プライムシューターベッチュー", "zh": "剑乌贼丸贴牌精英枪"},
	80: {"en": ".96 Gal", "fr": "Calibre 3000", "es": "Salpicadora 3000", "de": ".96 Gallon", "it": "Calibro 3000", "ru": "Струевик .96", "ja": ".96ガロン", "zh": ".96加仑"},
	81: {"en": ".96 Gal Deco", "fr": "Calibre 3000 chic", "es": "Salpicadora 3000 DX", "de": ".96 Gallon Deko", "it": "Calibro 3000 DX", "ru": "Струевик .96 «Деко»", "ja": ".96ガロンデコ", "zh": ".96加仑 装饰"},
	90: {"en": "Jet Squelcher", "fr": "Nettoyeur XL", "es": "Megabarredora", "de": "Platscher", "it": "Sweeper", "ru": "Плескарь", "ja": "ジェットスイーパー", "zh": "喷射清洁枪"},
	91: {"en": "Custom Jet Squelcher", "fr": "Nettoyeur XL modifié", "es": "Megabarredora SP", "de": "Platscher SE", "it": "Sweeper CM", "ru": "Плескарь «Понт»", "ja": "ジェットスイーパーカスタム", "zh": "喷射清洁枪 改装"},
	200: {"en": "Luna Blaster", "fr": "Proxiblaster", "es": "Ultradevastador", "de": "Luna-Blaster", "it": "Blaster lunar", "ru": "Лунобластер", "ja": "ノヴァブラスター", "zh": "新星爆破枪"},
	201: {"en": "Luna Blaster Neo", "fr": "Proxiblaster Néo", "es": "Ultradevastador neo", "de": "Luna-Blaster Neo", "it": "Blaster lunar Neo", "ru": "Лунобластер «Нео»", "ja": "ノヴァブラスターネオ", "zh": "新星爆破枪 新型"},
	202: {"en": "Kensa Luna Blaster", "fr": "Proxiblaster K", "es": "Ultradevastador elegante", "de": "Kensa-Luna-Blaster", "it": "Blaster lunar Nero Marlin", "ru": "Лунобластер от С. Кусаки", "ja": "ノヴァブラスターベッチュー", "zh": "剑乌贼丸贴牌月亮泡枪"},
	210: {"en": "Blaster", "fr": "Éclablaster", "es": "Devastador", "de": "Blaster", "it": "Blaster", "ru": "Бластер", "ja": "ホットブラスター", "zh": "火热爆破枪"},
	211: {"en": "Custom Blaster", "fr": "Éclablaster modifié", "es": "Devastador SP", "de": "Blaster SE", "it": "Blaster CM", "ru": "Бластер «Понт»", "ja": "ホットブラスターカスタム", "zh": "火热爆破枪 改装"},
	215: {"en": "Hero Blaster Replica", "fr": "Blaster héroïque (réplique)", "es": "Devastador de élite (réplica)", "de": "Helden-Blaster Replik", "it": "Blaster élite replica", "ru": "Бластер-004 (клон)", "ja": "ヒーローブラスター レプリカ", "zh": "复刻英雄热泡枪"},
	220: {"en": "Range Blaster", "fr": "Éclablaster XL", "es": "Teledevastador", "de": "Fern-Blaster", "it": "Blaster a distanza", "ru": "Дальнобластер", "ja": "ロングブラスター", "zh": "远距爆破枪"},
	221: {"en": "Custom Range Blaster", "fr": "Éclablaster XL griffé", "es": "Teledevastador SP", "de": "Fern-Blaster SE", "it": "Blaster a distanza CM", "ru": "Дальнобластер «Понт»", "ja": "ロングブラスターカスタム", "zh": "远距爆破枪 改装"},
	222: {"en": "Grim Range Blaster", "fr": "Éclablaster Nox", "es": "Teledevastador tétrico", "de": "Fern-Blaster Inferno", "it": "Blaster a distanza dark", "ru": "Дальнобластер «Мрак»", "ja": "ロングブラスターネクロ", "zh": "绿色长热泡"},
	230: {"en": "Clash Blaster", "fr": "Rafablaster", "es": "Turbodevastador", "de": "Kontra-Blaster", "it": "Blaster da mischia", "ru": "Контрабластер", "ja": "クラッシュブラスター", "zh": "冲涂爆破枪"},
	231: {"en": "Clash Blaster Neo", "fr": "Rafablaster Néo", "es": "Turbodevastador neo", "de": "Kontra-Blaster Neo", "it": "Blaster da mischia Neo", "ru": "Контрабластер «Нео»", "ja": "クラッシュブラスターネオ", "zh": "冲涂爆破枪 新型"},
	240: {"en": "Rapid Blaster", "fr": "Turboblaster", "es": "Devastador exprés", "de": "Turbo-Blaster", "it": "Blaster rapido", "ru": "Бластермат", "ja": "ラピッドブラスター", "zh": "快速爆破枪"},
	241: {"en": "Rapid Blaster Deco", "fr": "Turboblaster chic", "es": "Devastador exprés DX", "de": "Turbo-Blaster Deko", "it": "Blaster rapido DX", "ru": "Бластермат «Деко»", "ja": "ラピッドブラスターデコ", "zh": "快速爆破枪 装饰"},
	242: {"en": "Kensa Rapid Blaster", "fr": "Turboblaster K", "es": "Devastador exprés elegante", "de": "Kensa-Turbo-Blaster", "it": "Blaster rapido Nero Marlin", "ru": "Бластермат от С. Кусаки", "ja": "ラピッドブラスターベッチュー", "zh": "剑乌贼丸贴牌红色快速泡枪"},
	250: {"en": "Rapid Blaster Pro", "fr": "Turboblaster pro", "es": "Superdevastador", "de": "Turbo-Blaster Plus", "it": "Blaster élite", "ru": "Бластермат ПРО", "ja": "Rブラスターエリート", "zh": "快速爆破枪 精英"},
	251: {"en": "Rapid Blaster Pro Deco", "fr": "Turboblaster pro chic", "es": "Superdevastador DX", "de": "Turbo-Blaster Plus Deko", "it": "Blaster élite DX", "ru": "Бластермат ПРО «Деко»", "ja": "Rブラスターエリートデコ", "zh": "快速爆破枪 精英装饰"},
	300: {"en": "L-3 Nozzlenose", "fr": "Arroseur léger", "es": "Tintambor ligero", "de": "L3 Tintenwerfer", "it": "Triplete compatto", "ru": "Каплетрон-компакт", "ja": "L3リールガン", "zh": "L3卷管枪"},
	301: {"en": "L-3 Nozzlenose D", "fr": "Arroseur léger Cétacé", "es": "Tintambor ligero D", "de": "L3 Tintenwerfer D", "it": "Triplete compatto D", "ru": "Каплетрон-компакт 2.0", "ja": "L3リールガンD", "zh": "L3卷管枪D"},
	302: {"en": "Kensa L-3 Nozzlenose", "fr": "Arroseur léger K", "es": "Tintambor ligero elegante", "de": "Kensa-L3-Tintenwerfer", "it": "Triplete compatto Nero Marlin", "ru": "Каплетрон-компакт С.К.", "ja": "L3リールガンベッチュー", "zh": "剑乌贼丸贴牌L-3水枪"},
	310: {"en": "H-3 Nozzlenose", "fr": "Arroseur lourd", "es": "Tintambor pesado", "de": "S3 Tintenwerfer", "it": "Triplete", "ru": "Тяжелый каплетрон", "ja": "H3リールガン", "zh": "H3卷管枪"},
	311: {"en": "H-3 Nozzlenose D", "fr": "Arroseur lourd Cétacé", "es": "Tintambor pesado D", "de": "S3 Tintenwerfer D", "it": "Triplete D", "ru": "Тяжелый каплетрон 2.0", "ja": "H3リールガンD", "zh": "H3卷管枪D"},
	312: {"en": "Cherry H-3 Nozzlenose", "fr": "Arroseur lourd Cerise", "es": "Tintambor pesado cereza", "de": "S3 Tintenwerfer Kirsch", "it": "Triplete ciliegia", "ru": "Т-каплетрон «Вишня»", "ja": "H3リールガンチェリー", "zh": "樱桃H3水枪"},
	400: {"en": "Squeezer", "fr": "Compresseur", "es": "Tintopresor", "de": "Quetscher", "it": "Strizzer", "ru": "Бутылятор", "ja": "ボトルガイザー", "zh": "开瓶喷泉枪"},
	401: {"en": "Foil Squeezer", "fr": "Compresseur alu", "es": "Tintopresor B", "de": "Quetscher Fol", "it": "Strizzer B", "ru": "Бутылятор «Блеск»", "ja": "ボトルガイザーフォイル", "zh": "开瓶喷泉枪 金属箔"},
	1000: {"en": "Carbon Roller", "fr": "Rouleau carbone", "es": "Rodillo de carbono", "de": "Karbonroller", "it": "Rullo di carbonio", "ru": "Валик ЛАЙТ", "ja": "カーボンローラー", "zh": "碳纤维滚筒"},
	1001: {"en": "Carbon Roller Deco", "fr": "Rouleau carbone chic", "es": "Rodillo de carbono DX", "de": "Karbonroller Deko", "it": "Rullo di carbonio DX", "ru": "Валик ЛАЙТ «Деко»", "ja": "カーボンローラーデコ", "zh": "碳纤维滚筒 装饰"},
	1010: {"en": "Splat Roller", "fr": "Rouleau", "es": "Rodillo básico", "de": "Klecksroller", "it": "Rullo splat", "ru": "Сплат-валик", "ja": "スプラローラー", "zh": "斯普拉滚筒"},
	1011: {"en": "Krak-On Splat Roller", "fr": "Rouleau griffé", "es": "Rodillo básico B", "de": "Medusa-Klecksroller", "it": "Rullo splat logo", "ru": "Сплат-валик «Кра-Кен»", "ja": "スプラローラーコラボ", "zh": "斯普拉滚筒 联名"},
	1012: {"en": "Kensa Splat Roller", "fr": "Rouleau K", "es": "Rodillo básico elegante", "de": "Kensa-Klecksroller", "it": "Rullo splat Nero Marlin", "ru": "Валик от С. Кусаки", "ja": "スプラローラーベッチュー", "zh": "剑乌贼丸贴牌滚筒"},
	1015: {"en": "Hero Roller Replica", "fr": "Rouleau héroïque (réplique)", "es": "Rodillo de élite (réplica)", "de": "Helden-Roller Replik", "it": "Rullo élite replica", "ru": "Валик-004 (клон)", "ja": "ヒーローローラー レプリカ", "zh": "复刻英雄滚筒"},
	1020: {"en": "Dynamo Roller", "fr": "Dynamo-rouleau", "es": "Dinamorrodillo", "de": "Dynaroller", "it": "Rullo dinamo", "ru": "Мотовалик", "ja": "ダイナモローラー", "zh": "电动马达滚筒"},
	1021: {"en": "Gold Dynamo Roller", "fr": "Dynamo-rouleau tesla", "es": "Dinamorrodillo T", "de": "Dynaroller Tesla", "it": "Rullo dinamo dorato", "ru": "Мотовалик VIP", "ja": "ダイナモローラーテスラ", "zh": "电动马达滚筒 高磁波"},
	1022: {"en": "Kensa Dynamo Roller", "fr": "Dynamo-rouleau K", "es": "Dinamorrodillo elegante", "de": "Kensa-Dynaroller", "it": "Rullo dinamo Nero Marlin", "ru": "Мотовалик от С. Кусаки", "ja": "ダイナモローラーベッチュー", "zh": "剑乌贼丸贴牌重刷"},
	1030: {"en": "Flingza Roller", "fr": "Flexi-rouleau", "es": "Rodillo versátil", "de": "Flex-Roller", "it": "Flexi-rullo", "ru": "Омнивалик", "ja": "ヴァリアブルローラー", "zh": "可变式滚筒"},
	1031: {"en": "Foil Flingza Roller", "fr": "Flexi-rouleau alu", "es": "Rodillo versátil B", "de": "Flex-Roller Fol", "it": "Flexi-rullo B", "ru": "Омнивалик «Блеск»", "ja": "ヴァリアブルローラーフォイル", "zh": "可变式滚筒 金属箔"},
	1100: {"en": "Inkbrush", "fr": "Épinceau", "es": "Pincel", "de": "Quasto", "it": "Calamaravaggio", "ru": "Кисть", "ja": "パブロ", "zh": "巴勃罗"},
	1101: {"en": "Inkbrush Nouveau", "fr": "Épinceau nuancé", "es": "Pincel maestro", "de": "Quasto Fresco", "it": "Calamaravaggio master", "ru": "Кисть «НуВо»", "ja": "パブロ・ヒュー", "zh": "巴勃罗·新艺术"},
	1102: {"en": "Permanent Inkbrush", "fr": "Épinceau permanent", "es": "Pincel perpetuo", "de": "Quasto Permanent", "it": "Calamaravaggio indelebile", "ru": "Водостойкая кисть", "ja": "パーマネント・パブロ", "zh": "永久毛刷"},
	1110: {"en": "Octobrush", "fr": "Épinceau brosse", "es": "Brocha", "de": "Kalligraf", "it": "Tinturicchio", "ru": "Арт-кисть", "ja": "ホクサイ", "zh": "北斋"},
	1111: {"en": "Octobrush Nouveau", "fr": "Épinceau brosse nuancé", "es": "Brocha maestra", "de": "Kalligraf Fresco", "it": "Tinturicchio master", "ru": "Арт-кисть «НуВо»", "ja": "ホクサイ・ヒュー", "zh": "北斋·新艺术"},
	1112: {"en": "Kensa Octobrush", "fr": "Épinceau K", "es": "Brocha elegante", "de": "Kensa-Kalligraf", "it": "Tinturicchio Nero Marlin", "ru": "Арт-кисть от С. Кусаки", "ja": "ホクサイベッチュー", "zh": "剑乌贼丸贴牌北斋重刷"},
	1115: {"en": "Herobrush Replica", "fr": "Épinceau héroïque (réplique)", "es": "Brocha de élite (réplica)", "de": "Helden-Pinsel Replik", "it": "Pennello élite replica", "ru": "Кисть-004 (клон)", "ja": "ヒーローブラシ レプリカ", "zh": "复刻英雄刷"},
	2000: {"en": "Classic Squiffer", "fr": "Décap'express Alpha", "es": "Kalarrapid α", "de": "Sepiator α", "it": "Kalamarapid α", "ru": "Стиратель", "ja": "スクイックリンα", "zh": "鱿快洁α"},
	2001: {"en": "New Squiffer", "fr": "Décap'express Bêta", "es": "Kalarrapid β", "de": "Sepiator β", "it": "Kalamarapid β", "ru": "Стиратель-II", "ja": "スクイックリンβ", "zh": "鱿快洁β"},
	2002: {"en": "Fresh Squiffer", "fr": "Décap'express Gamma", "es": "Kalarrapid γ", "de": "Sepiator γ", "it": "Kalamarapid γ", "ru": "Стиратель «Свежесть»", "ja": "スクイックリンγ", "zh": "新鲜贴牌洗洁精狙击枪"},
	2010: {"en": "Splat Charger", "fr": "Concentraceur", "es": "Cargatintas", "de": "Klecks-Konzentrator", "it": "Splatter a carica", "ru": "Сплатган", "ja": "スプラチャージャー", "zh": "斯普拉蓄力狙击枪"},
	2011: {"en": "Firefin Splat Charger", "fr": "Concentraceur griffé", "es": "Cargatintas Chokkor", "de": "Rilax-Klecks-Konzentrator", "it": "Splatter a carica logo", "ru": "Сплатган «Фритюр»", "ja": "スプラチャージャーコラボ", "zh": "火河豚绿色狙击枪"},
	2012: {"en": "Kensa Charger", "fr": "Concentraceur K", "es": "Cargatintas elegante", "de": "Kensa-Klecks-Konzentrator", "it": "Splatter a carica Nero Marlin", "ru": "Сплатган от С. Кусаки", "ja": "スプラチャージャーベッチュー", "zh": "剑乌贼丸贴牌狙击枪"},
	2015: {"en": "Hero Charger Replica", "fr": "Conc. héroïque (réplique)", "es": "Cargatintas de élite (réplica)", "de": "Helden-Konzentrator Replik", "it": "Splatter élite replica", "ru": "Сплатган-004 (клон)", "ja": "ヒーローチャージャー レプリカ", "zh": "复刻英雄狙击枪"},
	2020: {"en": "Splatterscope", "fr": "Concentraceur zoom", "es": "Cargatintas con mira", "de": "Ziel-Konzentrator", "it": "Splatter con mirino", "ru": "Снайпокрас", "ja": "スプラスコープ", "zh": "斯普拉准星枪"},
	2021: {"en": "Firefin Splatterscope", "fr": "Concentraceur zoom griffé", "es": "Cargatintas con mira Chokkor", "de": "Rilax-Ziel-Konzentrator", "it": "Splatter con mirino logo", "ru": "Снайпокрас «Фритюр»", "ja": "スプラスコープコラボ", "zh": "火河豚带镜狙击枪"},
	2022: {"en": "Kensa Splatterscope", "fr": "Concentraceur zoom K", "es": "Cargatintas con mira elegante", "de": "Kensa-Ziel-Konzentrator", "it": "Splatter con mirino Nero Marlin", "ru": "Снайпокрас от С. Кусаки", "ja": "スプラスコープベッチュー", "zh": "剑乌贼丸贴牌带镜狙击枪"},
	2030: {"en": "E-liter 4K", "fr": "Extraceur +", "es": "Entintador 4K", "de": "E-liter 4K", "it": "Tinter a carica 4K", "ru": "Э-литр 95", "ja": "リッター4K", "zh": "公升4K"},
	2031: {"en": "Custom E-liter 4K", "fr": "Extraceur + modifié", "es": "Entintador 4K SP", "de": "E-liter 4K SE", "it": "Tinter a carica 4K CM", "ru": "Э-литр 95 «Понт»", "ja": "リッター4Kカスタム", "zh": "公升4K 改装"},
	2040: {"en": "E-liter 4K Scope", "fr": "Extraceur + zoom", "es": "Telentintador 4K", "de": "Ziel-E-liter 4K", "it": "Tinter con mirino 4K", "ru": "Снайп-э-литр 95", "ja": "4Kスコープ", "zh": "4K准星枪"},
	2041: {"en": "Custom E-liter 4K Scope", "fr": "Extraceur + zoom modifié", "es": "Telentintador 4K SP", "de": "Ziel-E-liter 4K SE", "it": "Tinter con mirino 4K CM", "ru": "Снайп-э-литр 95 «Понт»", "ja": "4Kスコープカスタム", "zh": "4K准星枪 改装"},
	2050: {"en": "Bamboozler 14 Mk I", "fr": "Bimbamboum Mk I", "es": "Bambufusil 14-I", "de": "Klotzer 14-A", "it": "Bimbamboom 14-I", "ru": "Бамбух 14-I", "ja": "14式竹筒銃・甲", "zh": "14式竹筒枪·甲"},
	2051: {"en": "Bamboozler 14 Mk II", "fr": "Bimbamboum Mk II", "es": "Bambufusil 14-II", "de": "Klotzer 14-B", "it": "Bimbamboom 14-II", "ru": "Бамбух 14-II", "ja": "14式竹筒銃・乙", "zh": "14式竹筒枪·乙"},
	2052: {"en": "Bamboozler 14 Mk III", "fr": "Bimbamboum Mk III", "es": "Bambufusil 14-III", "de": "Klotzer 14-C", "it": "Bimbamboom 14-III", "ru": "Бамбух 14-III", "ja": "14式竹筒銃・丙", "zh": "竹狙三代"},
	2060: {"en": "Goo Tuber", "fr": "Détubeur", "es": "Tubofusil", "de": "T-Tuber", "it": "Tintubator", "ru": "Трубастер", "ja": "ソイチューバー", "zh": "高压油管枪"},
	2061: {"en": "Custom Goo Tuber", "fr": "Détubeur modifié", "es": "Tubofusil SP", "de": "T-Tuber SE", "it": "Tintubator CM", "ru": "Трубастер «Понт»", "ja": "ソイチューバーカスタム", "zh": "高压油管枪 改装"},
	3000: {"en": "Slosher", "fr": "Seauceur", "es": "Derramatic", "de": "Schwapper", "it": "Secchiostro", "ru": "Ведроган", "ja": "バケットスロッシャー", "zh": "飞溅泼桶"},
	3001: {"en": "Slosher Deco", "fr": "Seauceur chic", "es": "Derramatic DX", "de": "Schwapper Deko", "it": "Secchiostro DX", "ru": "Ведроган «Деко»", "ja": "バケットスロッシャーデコ", "zh": "飞溅泼桶 装饰"},
	3002: {"en": "Soda Slosher", "fr": "Seauceur Diabolo", "es": "Derramatic centella", "de": "Sprudel-Schwapper", "it": "Secchiostro frizzante", "ru": "Ведроган «Содовый»", "ja": "バケットスロッシャーソーダ", "zh": "苏打水桶"},
	3005: {"en": "Hero Slosher Replica", "fr": "Seauceur héroïque (réplique)", "es": "Derramatic de élite (réplica)", "de": "Helden-Schwapper Replik", "it": "Secchiostro élite replica", "ru": "Ведроган-004 (клон)", "ja": "ヒーロースロッシャー レプリカ", "zh": "复刻英雄痛"},
	3010: {"en": "Tri-Slosher", "fr": "Dépoteur", "es": "Derramatic triple", "de": "3R-Schwapper", "it": "Secchiostro triplo", "ru": "Ведроган 3 в 1", "ja": "ヒッセン", "zh": "洗笔桶"},
	3011: {"en": "Tri-Slosher Nouveau", "fr": "Dépoteur nuancé", "es": "Derramatic triple maestro", "de": "3R-Schwapper Fresco", "it": "Secchiostro triplo master", "ru": "Ведроган 3 в 1 «НуВо»", "ja": "ヒッセン・ヒュー", "zh": "洗笔桶·新艺术"},
	3020: {"en": "Sloshing Machine", "fr": "Encrifugeur", "es": "Derramatic centrífugo", "de": "Trommel-Schwapper", "it": "Secchiostro centrifuga", "ru": "Центрифугер", "ja": "スクリュースロッシャー", "zh": "回旋泼桶"},
	3021: {"en": "Sloshing Machine Neo", "fr": "Encrifugeur Néo", "es": "Derramatic centrífugo neo", "de": "Trommel-Schwapper Neo", "it": "Secchiostro centrifuga Neo", "ru": "Центрифугер «Нео»", "ja": "スクリュースロッシャーネオ", "zh": "回旋泼桶 新型"},
	3022: {"en": "Kensa Sloshing Machine", "fr": "Encrifugeur K", "es": "Derramatic centrífugo elegante", "de": "Kensa-Trommel-Schwapper", "it": "Secchiostro centrifuga Nero Marlin", "ru": "Центрифугер от С. Кусаки", "ja": "スクリュースロッシャーベッチュー", "zh": "剑乌贼丸贴牌重型水桶"},
	3030: {"en": "Bloblobber", "fr": "Bassineur", "es": "Derramatic baño", "de": "Wannen-Schwapper", "it": "Secchiostro vasca", "ru": "Ваннаган", "ja": "オーバーフロッシャー", "zh": "满溢泡澡泼桶"},
	3031: {"en": "Bloblobber Deco", "fr": "Bassineur chic", "es": "Derramatic baño DX", "de": "Wannen-Schwapper Deko", "it": "Secchiostro vasca DX", "ru": "Ваннаган «Деко»", "ja": "オーバーフロッシャーデコ", "zh": "满溢泡澡泼桶 装饰"},
	3040: {"en": "Explosher", "fr": "Détoneur", "es": "Derramatic turbo", "de": "Knall-Schwapper", "it": "Termosecchiostro", "ru": "Шпарган", "ja": "エクスプロッシャー", "zh": "爆炸泼桶"},
	3041: {"en": "Custom Explosher", "fr": "Détoneur modifié", "es": "Derramatic turbo SP", "de": "Knall-Schwapper SE", "it": "Termosecchiostro master", "ru": "Шпарган «Понт»", "ja": "エクスプロッシャーカスタム", "zh": "爆炸泼桶 改装"},
	4000: {"en": "Mini Splatling", "fr": "Badigeonneur XS", "es": "Tintralladora ligera", "de": "Klecks-Splatling", "it": "Mini splatling", "ru": "Брызгомет-М", "ja": "スプラスピナー", "zh": "斯普拉旋转枪"},
	4001: {"en": "Zink Mini Splatling", "fr": "Badigeonneur XS griffé", "es": "Tintralladora ligera B", "de": "Sagitron-Klecks-Splatling", "it": "Mini splatling logo", "ru": "Брызгомет-М «Шпротус»", "ja": "スプラスピナーコラボ", "zh": "斯普拉旋转枪 联名"},
	4002: {"en": "Kensa Mini Splatling", "fr": "Badigeonneur XS K", "es": "Tintralladora ligera elegante", "de": "Kensa-Klecks-Splatling", "it": "Mini splatling Nero Marlin", "ru": "Брызгомет-М от С. Кусаки", "ja": "スプラスピナーベッチュー", "zh": "剑乌贼丸贴牌迷你加特林"},
	4010: {"en": "Heavy Splatling", "fr": "Badigeonneur", "es": "Tintralladora", "de": "Splatling", "it": "Splatling a tanica", "ru": "Брызгомет XL", "ja": "バレルスピナー", "zh": "桶装旋转枪"},
	4011: {"en": "Heavy Splatling Deco", "fr": "Badigeonneur chic", "es": "Tintralladora DX", "de": "Splatling Deko", "it": "Splatling a tanica DX", "ru": "Брызгомет XL «Деко»", "ja": "バレルスピナーデコ", "zh": "桶装旋转枪 装饰"},
	4012: {"en": "Heavy Splatling Remix", "fr": "Badigeonneur Disco", "es": "Tintralladora tecno", "de": "Splatling Ultrabass", "it": "Splatling a tanica techno", "ru": "Брызгомет XL «Ремикс»", "ja": "バレルスピナーリミックス", "zh": "混音贴牌重型加特林"},
	4015: {"en": "Hero Splatling Replica", "fr": "Badigeonneur héroïque (réplique)", "es": "Tintralladora de élite (réplica)", "de": "Helden-Splatling Replik", "it": "Splatling élite replica", "ru": "Брызгомет-004 (клон)", "ja": "ヒーロースピナー レプリカ", "zh": "复刻英雄加特林"},
	4020: {"en": "Hydra Splatling", "fr": "Exteinteur", "es": "Extintador", "de": "Hydrant", "it": "Idrante", "ru": "Брызгомет «Горыныч»", "ja": "ハイドラント", "zh": "消防栓旋转枪"},
	4021: {"en": "Custom Hydra Splatling", "fr": "Exteinteur modifié", "es": "Extintador SP", "de": "Hydrant SE", "it": "Idrante CM", "ru": "«Понт-Горыныч»", "ja": "ハイドラントカスタム", "zh": "消防栓旋转枪 改装"},
	4030: {"en": "Ballpoint Splatling", "fr": "Badigeonneur stylo", "es": "Ametrallógrafo", "de": "Kuli-Splatling", "it": "Tetrapenna", "ru": "Кугельшрайбер", "ja": "クーゲルシュライバー", "zh": "圆珠笔"},
	4031: {"en": "Ballpoint Splatling Nouveau", "fr": "Badigeonneur stylo nuancé", "es": "Ametrallógrafo maestro", "de": "Kuli-Splatling Fresco", "it": "Tetrapenna master", "ru": "Кугельшрайбер «НуВо»", "ja": "クーゲルシュライバー・ヒュー", "zh": "圆珠笔·新艺术"},
	4040: {"en": "Nautilus 47", "fr": "Nautilus 47", "es": "Subtralladora 47", "de": "Nautilus 47", "it": "Nautilus 47", "ru": "Наутилус-47", "ja": "ノーチラス47", "zh": "鹦鹉螺号47"},
	4041: {"en": "Nautilus 79", "fr": "Nautilus 79", "es": "Subtralladora 79", "de": "Nautilus 79", "it": "Nautilus 79", "ru": "Наутилус-79", "ja": "ノーチラス79", "zh": "鹦鹉螺号79"},
	5000: {"en": "Dapple Dualies", "fr": "Double moucheteur", "es": "Atomizador dual", "de": "Sprenkler", "it": "Ripolpella duplo", "ru": "Импрессиометы", "ja": "スパッタリー", "zh": "溅镀枪"},
	5001: {"en": "Dapple Dualies Nouveau", "fr": "Double moucheteur nuancé", "es": "Atomizador dual maestro", "de": "Sprenkler Fresco", "it": "Ripolpella duplo master", "ru": "Импрессиометы «НуВо»", "ja": "スパッタリー・ヒュー", "zh": "溅镀枪·新艺术"},
	5002: {"en": "Clear Dapple Dualies", "fr": "Double moucheteur dépoli", "es": "Atomizador dual sencillo", "de": "Sprenkler Claro", "it": "Ripolpella duplo minimal", "ru": "Импрессиометы «Белизна»", "ja": "スパッタリークリア", "zh": "白色牙刷双枪"},
	5010: {"en": "Splat Dualies", "fr": "Double encreur", "es": "Difusor dual", "de": "Klecks-Doppler", "it": "Repolper duplo", "ru": "Спуртометы", "ja": "スプラマニューバー", "zh": "斯普拉机动枪"},
	5011: {"en": "Enperry Splat Dualies", "fr": "Double encreur griffé", "es": "Difusor dual B", "de": "Enperry-Klecks-Doppler", "it": "Repolper duplo logo", "ru": "Спуртометы «К.К.»", "ja": "スプラマニューバーコラボ", "zh": "斯普拉机动枪 联名"},
	5012: {"en": "Kensa Splat Dualies", "fr": "Double encreur K", "es": "Difusor dual elegante", "de": "Kensa-Klecks-Doppler", "it": "Repolper duplo Nero Marlin", "ru": "Спуртометы от С. Кусаки", "ja": "スプラマニューバーベッチュー", "zh": "剑乌贼丸贴牌双枪"},
	5015: {"en": "Hero Dualie Replicas", "fr": "Double encreur héroïque (réplique)", "es": "Difusor dual de élite (réplica)", "de": "Helden-Doubler Replik", "it": "Repolper duplo élite replica", "ru": "Спуртометы-004 (клон)", "ja": "ヒーローマニューバー レプリカ", "zh": "复刻英雄双枪"},
	5020: {"en": "Glooga Dualies", "fr": "Double Kelvin 525", "es": "Fundidora 525 dual", "de": "Kelvin 525", "it": "Kelvin duplo 525", "ru": "Термоплюхи 525", "ja": "ケルビン525", "zh": "开尔文525"},
	5021: {"en": "Glooga Dualies Deco", "fr": "Double Kelvin 525 chic", "es": "Fundidora 525 dual DX", "de": "Kelvin 525 Deko", "it": "Kelvin duplo 525 DX", "ru": "Термоплюхи 525 «Деко»", "ja": "ケルビン525デコ", "zh": "开尔文525 装饰"},
	5022: {"en": "Kensa Glooga Dualies", "fr": "Double Kelvin 525 K", "es": "Fundidora 525 dual elegante", "de": "Kensa-Kelvin-525", "it": "Kelvin duplo 525 Nero Marlin", "ru": "Термоплюхи 525 от С. К.", "ja": "ケルビン525ベッチュー", "zh": "剑乌贼丸贴牌开尔文"},
	5030: {"en": "Dualie Squelchers", "fr": "Double nettoyeur", "es": "Barredora dual", "de": "Dual-Platscher", "it": "Sweeper duplo", "ru": "Спурт-плескари", "ja": "デュアルスイーパー", "zh": "双重清洁枪"},
	5031: {"en": "Custom Dualie Squelchers", "fr": "Double nettoyeur modifié", "es": "Barredora dual SP", "de": "Dual-Platscher SE", "it": "Sweeper duplo CM", "ru": "Спурт-плескари «Понт»", "ja": "デュアルスイーパーカスタム", "zh": "双重清洁枪 改装"},
	5040: {"en": "Dark Tetra Dualies", "fr": "Double voltigeur noir", "es": "Motatrónic dual negro", "de": "Quadhopper Noir", "it": "Moscarpino duplo nero", "ru": "Черные спуртокроссы", "ja": "クアッドホッパーブラック", "zh": "四重弹跳手枪 黑"},
	5041: {"en": "Light Tetra Dualies", "fr": "Double voltigeur blanc", "es": "Motatrónic dual blanco", "de": "Quadhopper Blanc", "it": "Moscarpino duplo bianco", "ru": "Белые спуртокроссы", "ja": "クアッドホッパーホワイト", "zh": "四重弹跳手枪 白"},
	6000: {"en": "Splat Brella", "fr": "Para-encre", "es": "Paratintas", "de": "Parapluviator", "it": "Sparasole", "ru": "Сплат-зонт", "ja": "パラシェルター", "zh": "遮阳防空伞"},
	6001: {"en": "Sorella Brella", "fr": "Para-encre Sorella", "es": "Paratintas B", "de": "Sorella-Parapluviator", "it": "Sparasole Solerra", "ru": "Зонтган «Родиччи»", "ja": "パラシェルターソレーラ", "zh": "遮阳防空伞 姐妹"},
	6005: {"en": "Hero Brella Replica", "fr": "Para-encre héroïque (réplique)", "es": "Paratintas de élite (réplica)", "de": "Helden-Pluviator Replik", "it": "Sparasole élite replica", "ru": "Зонтган-004 (клон)", "ja": "ヒーローシェルター レプリカ", "zh": "复刻英雄伞枪"},
	6010: {"en": "Tenta Brella", "fr": "Para-encre XL", "es": "Paratintas maxi", "de": "Camp-Pluviator", "it": "Sparatenda", "ru": "Зонтент", "ja": "キャンピングシェルター", "zh": "露营防空伞"},
	6011: {"en": "Tenta Sorella Brella", "fr": "Para-encre XL Sorella", "es": "Paratintas maxi B", "de": "Sorella-Camp-Pluviator", "it": "Sparatenda Solerra", "ru": "Зонтент «Родиччи»", "ja": "キャンピングシェルターソレーラ", "zh": "露营防空伞 姐妹"},
	6012: {"en": "Tenta Camo Brella", "fr": "Para-encre XL treillis", "es": "Paratintas maxi camuflaje", "de": "Camp-Pluviator Camo", "it": "Sparatenda mimetico", "ru": "Зонтент «Спецназ»", "ja": "キャンピングシェルターカーモ", "zh": "迷彩野营伞"},
	6020: {"en": "Undercover Brella", "fr": "Para-encre espion", "es": "Paratintas clásico", "de": "UnderCover", "it": "Bombrello", "ru": "Шпионский зонт", "ja": "スパイガジェット", "zh": "特工配件"},
	6021: {"en": "Undercover Sorella Brella", "fr": "Para-encre espion Sorella", "es": "Paratintas clásico B", "de": "Sorella-UnderCover", "it": "Bombrello Solerra", "ru": "Шпионский зонт «Родиччи»", "ja": "スパイガジェットソレーラ", "zh": "特工配件 姐妹"},
	6022: {"en": "Kensa Undercover Brella", "fr": "Para-encre espion K", "es": "Paratintas clásico elegante", "de": "Kensa-UnderCover", "it": "Bombrello Nero Marlin", "ru": "Шпионский зонт от С. К.", "ja": "スパイガジェットベッチュー", "zh": "剑乌贼丸贴牌间谍伞"},
}

// s2WeaponName returns the weapon name in the requested site language (English fallback).
func s2WeaponName(id uint32, lang string) string {
	m, ok := s2WeaponNames[id]
	if !ok {
		return ""
	}
	if v, ok := m[lang]; ok {
		return v
	}
	return m["en"]
}
